export const TOGGLE_SIMILAR_SHAPES_MODAL = 'TOGGLE_SIMILAR_SHAPES_MODAL';
export const FETCH_SIMILAR_SHAPES = 'FETCH_SIMILAR_SHAPES';
export const UPDATE_SIMILAR_SHAPES = 'UPDATE_SIMILAR_SHAPES';
export const SET_ACTIVE_SHAPE = 'SET_ACTIVE_SHAPE';
export const CHANGE_SHAPES_METRICS = 'CHANGE_SHAPES_METRICS';
