export const FocusChartConstants = {
    OFFSET_WIDTH: 55,
    OFFSET_HEIGHT: 110,
    MIN_VALUE: Number.MAX_SAFE_INTEGER,
    MAX_VALUE: Number.MIN_SAFE_INTEGER,
    CHART_WIDTH: 0,
    CHART_HEIGHT: 0,
    TRANSLATE_TOP: 88,
    TRANSLATE_LEFT: 38,
};
